export HF_HOME=/workspace/jyh/.cache/huggingface
/workspace/jyh/miniconda3/envs/llama_factory/bin/deepspeed --num_gpus 8 --master_port=9901 src/train_bash.py \
    --deepspeed ds_config.json \
    --stage sft \
    --do_train True \
    --model_name_or_path /workspace/jyh/LLaMA-Factory/chatglm3-6b \
    --finetuning_type lora \
    --template chatglm3 \
    --dataset_dir data \
    --dataset haruhi_zero_0,haruhi_zero_1,haruhi_zero_2,haruhi_zero_3,haruhi_zero_4,haruhi_zero_5 \
    --cutoff_len 1024 \
    --learning_rate 5e-03 \
    --num_train_epochs 3.0 \
    --max_samples 100000 \
    --per_device_train_batch_size 8 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --max_grad_norm 1.0 \
    --logging_steps 5 \
    --save_steps 100 \
    --warmup_steps 0 \
    --lora_rank 8 \
    --lora_dropout 0.1 \
    --lora_target query_key_value \
    --output_dir saves/ChatGLM3-6B-Chat/lora/train_2024-02-16-16-53 \
    --fp16 True \
    --plot_loss True